### ISSUE TITLE
Gitpod Internal: Cannot start apache

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel8-starter#46]
### Describe the bug
After building a new workspace image you get the following error when trying to start apache.
```
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
AH00014: Configuration check failed
Action 'start' failed.
The Apache error log may have more information.
```
### Screenshots

![image](https://user-images.githubusercontent.com/3060702/109993957-b0b33900-7cc1-11eb-8b22-fc2073beb7cf.png)

### Steps to reproduce

1. Create a new github project from this starter as per the instructions in README.md
2. Force the workspace image to build
    - In `.github.Dockerfile` increment the value for `INVALIDATE_CACHE`
3. Push the changed files to the repository.
4. Create a new workspace in gitpod
5. After the IDE is displayed start apache
    - In a terminal run `start_apache`

You will see the error:
```
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
AH00014: Configuration check failed
Action 'start' failed.
The Apache error log may have more information.
```

### Expected behavior
Apache should start.
`/var/log/apache2` should be created by default when the workspace image is built.

### Additional information
This is an internal gitpod bug and the fix is awaiting review.
https://github.com/gitpod-io/workspace-images/pull/362

### Workaround
Write the directory and files in `.gitpod.Dockerfile`
```bash
RUN sudo mkdir /var/log/apache2 \

    && sudo chmod 755 /var/log/apache2

RUN sudo touch /var/log/apache2/access.log \

    && sudo chmod 666 /var/log/apache2/access.log

RUN sudo touch /var/log/apache2/error.log \

    && sudo chmod 666 /var/log/apache2/error.log

RUN sudo touch /var/log/apache2/other_vhosts_access.log \

    && sudo chmod 666 /var/log/apache2/other_vhosts_access.log
```

**Comment by aledbf** [comment]
@apolopena please test the image `aledbf/workspace-mysql:04032021`. It contains the fix in gitpod-io/workspace-images#362

**Comment by apolopena** [comment]
No worries, thanks for the speedy response. I am on it, will let you know the results soon.

**Comment by apolopena** [comment]
@alefbd, 
Yes I can verify that the issue is resolved.

**Comment by apolopena** [comment]
Awaiting https://github.com/gitpod-io/workspace-images/pull/362

**Comment by apolopena** [comment]
Implementing the [workaround](https://github.com/apolopena/gitpod-laravel8-starter/issues/46#issue-822288039) for now so I can get the [latest batch of changes](https://github.com/apolopena/gitpod-laravel8-starter/commit/b892185f1b3b4c81d124738d088fd98f00f7fa4f) tested. No need to restest the latest batch of changes once the fix is in because the nature of the issue is so simple.

**Comment by apolopena** [comment]
Workaround breaks the workspace image build now.
![image](https://user-images.githubusercontent.com/3060702/112190475-473c9100-8bc2-11eb-82af-bc5fc7ae498f.png)

Gitpod PR [362](https://github.com/gitpod-io/workspace-images/pull/362) has been merged live 🚀
I am removing the workaround and will report the final on results here.

**Comment by apolopena** [comment]
Apache logs are built by the gitpod image now. Workaround has been removed.

**Comment by apolopena** [comment]
will keep open untill pushed live.
